server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5433/elearning_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.application.name=backend
spring.jpa.database=PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.max-tokens=4096
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
file.upload-dir=uploads
spring.servlet.multipart.enabled=true
# ================================================
# RAG - PgVector Store
# ================================================
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

spring.ai.embedding.transformer.onnx.model-uri=https://huggingface.co/Xenova/bge-base-en-v1.5/resolve/main/onnx/model.onnx
spring.ai.embedding.transformer.tokenizer.uri=https://huggingface.co/Xenova/bge-base-en-v1.5/resolve/main/tokenizer.json
spring.ai.vectorstore.pgvector.dimensions=768

# Désactiver les embeddings OpenAI (évite conflit de beans)
# On garde OpenAI UNIQUEMENT pour le chat (Groq)
spring.ai.openai.embedding.enabled=false
